version: '3.4'

services:
  convergenceassignment:
    image: usersconvergenceassignment
    env_file: 
      .env.dev
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  mongo:
    container_name: convergence-mongo
    image: "mongo:latest"
    ports:
      - "27017:27017"