version: '3.4'

services:
  usersconvergenceassignmentdev:
    image: usersconvergenceassignmentdev
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["nodemon", "--inspect=0.0.0.0:9229", "src/index.js"]
    volumes:
      - ./:/usr/src/app
