version: '3.4'

services:
  convergenceassignmentdev:
    image: convergenceassignmentdev
    restart: always
    env_file: 
      .env.dev
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    depends_on:
      - mongo
    ports:
      - 3000:3000
      - 9229:9229
    command: sh -c "npm i;nodemon --ignore 'logs/*' --inspect=0.0.0.0:9229 src/index.js"
    volumes:
      - ./:/usr/app
  mongo:
    container_name: convergence-mongo-dev
    image: "mongo:latest"
    ports:
      - "27017:27017"