version: '3.4'

services:
  usersconvergenceassignment:
    image: usersconvergenceassignment
    env_file: 
      .env.dev
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
